{
    "drinks" [
        {
            "idDrink": "178370",
            "strDrink": "Mauresque",
            "strDrinkAlternate": null,
            "strTags": null,
            "strVideo": null,
            "strCategory": "Cocktail",
            "strIBA": null,
            "strAlcoholic": "Alcoholic",
            "strGlass": "Collins glass",
            "strInstructions": "1 - Pour the Ricard (or pastis)\r\n2 - Pour the orgeat syrup\r\n3 - Finally pour the water and add ice cubes at your convenience.\r\n\r\nAdd the ice cubes at the end, otherwise the syrup and pastis do not mix well.",
            "strInstructionsES": null,
            "strInstructionsDE": null,
            "strInstructionsFR": null,
            "strInstructionsIT": null,
            "strInstructionsZH-HANS": null,
            "strInstructionsZH-HANT": null,
            "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/duwfa11686236556.jpg",
            "strIngredient1": "Ricard",
            "strIngredient2": "Orgeat Syrup",
            "strIngredient3": "Water",
            "strIngredient4": "",
            "strIngredient5": "",
            "strIngredient6": "",
            "strIngredient7": "",
            "strIngredient8": null,
            "strIngredient9": null,
            "strIngredient10": null,
            "strIngredient11": null,
            "strIngredient12": null,
            "strIngredient13": null,
            "strIngredient14": null,
            "strIngredient15": null,
            "strMeasure1": "3 cl",
            "strMeasure2": "1 cl",
            "strMeasure3": "Full Glass",
            "strMeasure4": "",
            "strMeasure5": "",
            "strMeasure6": "",
            "strMeasure7": "",
            "strMeasure8": null,
            "strMeasure9": null,
            "strMeasure10": null,
            "strMeasure11": null,
            "strMeasure12": null,
            "strMeasure13": null,
            "strMeasure14": null,
            "strMeasure15": null,
            "strImageSource": "https://thecocktailist.fr/wp-content/uploads/2022/06/kitscocktails-mauresquedeluxe-1065.jpg",
            "strImageAttribution": null,
            "strCreativeCommonsConfirmed": "No",
            "dateModified": null
        },
        {
            "idDrink": "178369",
            "strDrink": "Cocktail Horse’s Neck",
            "strDrinkAlternate": null,
            "strTags": null,
            "strVideo": null,
            "strCategory": "Cocktail",
            "strIBA": null,
            "strAlcoholic": "Alcoholic",
            "strGlass": "Highball glass",
            "strInstructions": "Wash and brush an organic, untreated lemon, then cut a spiral of lemon peel, using a citrus peel. If it is too large, cut it with a sharp knife.\r\n\r\nPut some ice in a tall tumbler glass, place the lemon peel inside and pour the cognac, add the ginger beer and let 2-3 drops of Angostura fall into it. Easy to do, but once you try it you'll love it.",
            "strInstructionsES": null,
            "strInstructionsDE": "Waschen und bürsten Sie eine unbehandelte Bio-Zitrone, schneiden Sie dann mit einer Zitrusschale eine Spirale aus der Zitronenschale. Wenn es zu groß ist, schneiden Sie es mit einem scharfen Messer.\r\n\r\nEtwas Eis in ein hohes Tumbler-Glas geben, die Zitronenschale hineingeben und den Cognac aufgießen, das Ginger Beer dazugeben und 2-3 Tropfen Angostura hineintropfen lassen. Einfach zu machen, aber wenn Sie es einmal probiert haben, werden Sie es lieben.",
            "strInstructionsFR": null,
            "strInstructionsIT": "Lavate e spazzolate un limone biologico e non trattato, poi tagliate una spirale di buccia di limone, usando uno sbuccia agrumi. Se viene troppo larga tagliatela con un coltellino affilato.\r\n\r\nMettete del ghiaccio in un bicchiere tumbler alto, sistemate dentro la buccia di limone e versate il cognac, aggiungete la ginger beer e lasciate cadere dentro 2-3 gocce di Angostura. Facile da fare, ma una volta provato ve ne innamorerete.",
            "strInstructionsZH-HANS": null,
            "strInstructionsZH-HANT": null,
            "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/4vobt21643844913.jpg",
            "strIngredient1": "Cognac",
            "strIngredient2": "Ginger Beer",
            "strIngredient3": "Angostura Bitters",
            "strIngredient4": "Lemon Peel",
            "strIngredient5": null,
            "strIngredient6": null,
            "strIngredient7": null,
            "strIngredient8": null,
            "strIngredient9": null,
            "strIngredient10": null,
            "strIngredient11": null,
            "strIngredient12": null,
            "strIngredient13": null,
            "strIngredient14": null,
            "strIngredient15": null,
            "strMeasure1": "4 cl",
            "strMeasure2": "100 ml",
            "strMeasure3": "3 drops",
            "strMeasure4": "1",
            "strMeasure5": "",
            "strMeasure6": "",
            "strMeasure7": "",
            "strMeasure8": null,
            "strMeasure9": null,
            "strMeasure10": null,
            "strMeasure11": null,
            "strMeasure12": null,
            "strMeasure13": null,
            "strMeasure14": null,
            "strMeasure15": null,
            "strImageSource": "https://upload.wikimedia.org/wikipedia/commons/0/0f/Horses_Neck.JPG",
            "strImageAttribution": null,
            "strCreativeCommonsConfirmed": "No",
            "dateModified": null
        },
        {
            "idDrink": "178368",
            "strDrink": "Planter’s Punch",
            "strDrinkAlternate": null,
            "strTags": null,
            "strVideo": null,
            "strCategory": "Cocktail",
            "strIBA": null,
            "strAlcoholic": "Alcoholic",
            "strGlass": "Highball glass",
            "strInstructions": "Squeeze an orange and strain the juice. Put all the ingredients in a shaker filled with ice and shake for at least 12 seconds. Strain into a highball glass and decorate with a pineapple wedge or fruit of your choice.",
            "strInstructionsES": null,
            "strInstructionsDE": "Eine Orange auspressen und den Saft abseihen. Alle Zutaten in einen mit Eis gefüllten Shaker geben und mindestens 12 Sekunden schütteln. In ein Longdrinkglas abseihen und mit einer Ananasscheibe oder Früchten Ihrer Wahl dekorieren.",
            "strInstructionsFR": null,
            "strInstructionsIT": "Spremete un’arancia e filtratene il succo. Mettete tutti gli ingredienti in uno shaker colmo di ghiaccio e agitate per almeno 12 secondi. Versate filtrando in un bicchiere highball e decorate con uno spicchio d’ananas o frutta a piacere.",
            "strInstructionsZH-HANS": null,
            "strInstructionsZH-HANT": null,
            "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/jn6o251643844541.jpg",
            "strIngredient1": "Dark Rum",
            "strIngredient2": "Orange Juice",
            "strIngredient3": "Pineapple Juice",
            "strIngredient4": "Grenadine",
            "strIngredient5": "Sugar Syrup",
            "strIngredient6": "Angostura Bitters",
            "strIngredient7": null,
            "strIngredient8": null,
            "strIngredient9": null,
            "strIngredient10": null,
            "strIngredient11": null,
            "strIngredient12": null,
            "strIngredient13": null,
            "strIngredient14": null,
            "strIngredient15": null,
            "strMeasure1": "4.5 cL",
            "strMeasure2": "3 cl",
            "strMeasure3": "3.5 cl",
            "strMeasure4": "1 cl",
            "strMeasure5": "1 cl",
            "strMeasure6": "4 drops",
            "strMeasure7": "",
            "strMeasure8": null,
            "strMeasure9": null,
            "strMeasure10": null,
            "strMeasure11": null,
            "strMeasure12": null,
            "strMeasure13": null,
            "strMeasure14": null,
            "strMeasure15": null,
            "strImageSource": "https://upload.wikimedia.org/wikipedia/commons/1/10/Planters_Punch_2.jpg",
            "strImageAttribution": null,
            "strCreativeCommonsConfirmed": "No",
            "dateModified": null
        },
        {
            "idDrink": "178367",
            "strDrink": "Ramos Gin Fizz",
            "strDrinkAlternate": null,
            "strTags": null,
            "strVideo": null,
            "strCategory": "Cocktail",
            "strIBA": null,
            "strAlcoholic": "Alcoholic",
            "strGlass": "Highball glass",
            "strInstructions": "Prepare all the ingredients on the counter to be able to work well and quickly, especially the cream and egg white.\r\n\r\nPour all the ingredients into a shaker.\r\n\r\nShake vigorously for 1 minute: cream and egg white must be mixed perfectly, so don't rush.\r\n\r\nNow open the shaker and put some ice and shake for 1-2 minutes. It depends on how long you can resist!\r\n\r\nPour into a highball glass, add a splash of soda and garnish to taste.\r\n\r\nRamos Gin Fizz was once drunk as an invigorating drink or even as a breakfast, try it as an aperitif and after dinner and you will discover a little gem now lost.",
            "strInstructionsES": null,
            "strInstructionsDE": "Bereiten Sie alle Zutaten auf der Theke vor, um gut und schnell arbeiten zu können, insbesondere die Sahne und das Eiweiß.\r\nAlle Zutaten, bis auf das Soda, in einen Shaker geben.\r\n1 Minute kräftig schütteln: Sahne und Eiweiß müssen sich perfekt vermischen, also keine Eile.\r\nJetzt den Shaker öffnen und etwas Eis hinzugeben und 1-2 Minuten schütteln. Es kommt darauf an, wie lange du widerstehen kannst!\r\nIn ein Longdrinkglas gießen, einen Spritzer Soda hinzugeben und nach Belieben garnieren.\r\nRamos Gin Fizz wurde einst als belebendes Getränk oder sogar als Frühstück getrunken, probieren Sie es als Aperitif und nach dem Abendessen und Sie werden ein kleines Juwel entdecken, das jetzt verloren gegangen ist.",
            "strInstructionsFR": null,
            "strInstructionsIT": "Preparate tutti gli ingredienti sul bancone per poter lavorare bene e velocemente, soprattutto la panna e l’albume d’uovo.\r\nVersate tutti gli ingredienti, a parte la soda, in uno shaker.\r\nAgitate energicamente per 1 minuto: panna ed albume si devono mescolare alla perfezione, quindi non abbiate fretta.\r\nAdesso aprite lo shaker e mettete un po’ di ghiaccio e agitate per 1-2 minuti. Dipende da quanto riuscite a resistere!\r\nVersate in un bicchiere highball, aggiungete uno schizzo di soda e guarnite a piacere.\r\nUna volta il Ramos Gin Fizz era bevuto come drink corroborante o addirittura come colazione, provatelo come aperitivo e nel dopo cena e scoprirete un piccolo gioiello ormai perduto.",
            "strInstructionsZH-HANS": null,
            "strInstructionsZH-HANT": null,
            "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/967t911643844053.jpg",
            "strIngredient1": "Gin",
            "strIngredient2": "Lemon Juice",
            "strIngredient3": "Sugar Syrup",
            "strIngredient4": "Cream",
            "strIngredient5": "Egg White",
            "strIngredient6": "Vanilla extract",
            "strIngredient7": "Soda Water",
            "strIngredient8": null,
            "strIngredient9": null,
            "strIngredient10": null,
            "strIngredient11": null,
            "strIngredient12": null,
            "strIngredient13": null,
            "strIngredient14": null,
            "strIngredient15": null,
            "strMeasure1": "4.5 cL",
            "strMeasure2": "3 cl",
            "strMeasure3": "3 cl",
            "strMeasure4": "6 cl",
            "strMeasure5": "1",
            "strMeasure6": "2 drop",
            "strMeasure7": "2 cl",
            "strMeasure8": null,
            "strMeasure9": null,
            "strMeasure10": null,
            "strMeasure11": null,
            "strMeasure12": null,
            "strMeasure13": null,
            "strMeasure14": null,
            "strMeasure15": null,
            "strImageSource": "https://cdn.diffords.com/contrib/stock-images/2021/08/610d32bab0377.jpg",
            "strImageAttribution": null,
            "strCreativeCommonsConfirmed": "No",
            "dateModified": null
        },
        {
            "idDrink": "178366",
            "strDrink": "Gin Lemon",
            "strDrinkAlternate": null,
            "strTags": "simple, classic, refreshing",
            "strVideo": null,
            "strCategory": "Cocktail",
            "strIBA": null,
            "strAlcoholic": "Alcoholic",
            "strGlass": "Highball glass",
            "strInstructions": "For the preparation of the gin lemon you will not need the shaker. Fill the tumbler with ice, pour the gin and lemonade over it. Gently mix and decorate with a slice of lemon. Those who prefer can also add a few mint leaves. Your gin lemon is ready to be served.",
            "strInstructionsES": null,
            "strInstructionsDE": "Für die Zubereitung des Gin Lemon benötigen Sie den Shaker nicht. Tumbler mit Eis füllen, Gin und Limonade darüber gießen. Vorsichtig mischen und mit einer Zitronenscheibe dekorieren. Wer möchte, kann auch noch ein paar Minzblätter hinzugeben. Ihr Gin Lemon ist servierfertig.",
            "strInstructionsFR": null,
            "strInstructionsIT": "Per la preparazione del gin lemon non vi servirà lo shaker. Riempite il tumbler con il ghiaccio, versateci sopra il gin e la limonata. Mescolate delicatamente e decorate con una fetta di limone. Chi preferisce potrà aggiungere anche qualche fogliolina di menta. Il vostro gin lemon è pronto per essere servito.",
            "strInstructionsZH-HANS": null,
            "strInstructionsZH-HANT": null,
            "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/6gdohq1681212476.jpg",
            "strIngredient1": "Gin",
            "strIngredient2": "Lemon Juice",
            "strIngredient3": "Lemon Peel",
            "strIngredient4": "Ice",
            "strIngredient5": null,
            "strIngredient6": null,
            "strIngredient7": null,
            "strIngredient8": null,
            "strIngredient9": null,
            "strIngredient10": null,
            "strIngredient11": null,
            "strIngredient12": null,
            "strIngredient13": null,
            "strIngredient14": null,
            "strIngredient15": null,
            "strMeasure1": "6 cl",
            "strMeasure2": "8 cl",
            "strMeasure3": "1 Slice",
            "strMeasure4": "cubes",
            "strMeasure5": "",
            "strMeasure6": "",
            "strMeasure7": "",
            "strMeasure8": null,
            "strMeasure9": null,
            "strMeasure10": null,
            "strMeasure11": null,
            "strMeasure12": null,
            "strMeasure13": null,
            "strMeasure14": null,
            "strMeasure15": null,
            "strImageSource": "https://www.pexels.com/photo/gin-and-tonic-cocktail-drinks-in-clear-glasses-4113155/",
            "strImageAttribution": "Leah Rolando",
            "strCreativeCommonsConfirmed": "Yes",
            "dateModified": null
        },
        {
            "idDrink": "178365",
            "strDrink": "Gin Tonic",
            "strDrinkAlternate": null,
            "strTags": null,
            "strVideo": null,
            "strCategory": "Cocktail",
            "strIBA": null,
            "strAlcoholic": "Alcoholic",
            "strGlass": "Highball glass",
            "strInstructions": "Fill a highball glass with ice, pour the gin, top with tonic water and squeeze a lemon wedge and garnish with a lemon wedge.",
            "strInstructionsES": null,
            "strInstructionsDE": "Füllen Sie ein Highball-Glas mit Eis, gießen Sie den Gin ein, gießen Sie Tonic Water darüber und drücken Sie eine Zitronenscheibe aus und garnieren Sie sie mit einer Zitronenscheibe.",
            "strInstructionsFR": null,
            "strInstructionsIT": "Colmate un bicchiere highball di ghiaccio, versate il gin, colmate con acqua tonica e spremete uno spicchio di limone e guarnite con una fetta di limone. ",
            "strInstructionsZH-HANS": null,
            "strInstructionsZH-HANT": null,
            "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/qcgz0t1643821443.jpg",
            "strIngredient1": "Gin",
            "strIngredient2": "Tonic Water",
            "strIngredient3": "Lemon Peel",
            "strIngredient4": "Ice",
            "strIngredient5": null,
            "strIngredient6": null,
            "strIngredient7": null,
            "strIngredient8": null,
            "strIngredient9": null,
            "strIngredient10": null,
            "strIngredient11": null,
            "strIngredient12": null,
            "strIngredient13": null,
            "strIngredient14": null,
            "strIngredient15": null,
            "strMeasure1": "4 cl",
            "strMeasure2": "10 cl",
            "strMeasure3": "1 Slice",
            "strMeasure4": "cubes",
            "strMeasure5": "",
            "strMeasure6": "",
            "strMeasure7": "",
            "strMeasure8": null,
            "strMeasure9": null,
            "strMeasure10": null,
            "strMeasure11": null,
            "strMeasure12": null,
            "strMeasure13": null,
            "strMeasure14": null,
            "strMeasure15": null,
            "strImageSource": "https://www.brunovanzan.com/wp-content/uploads/2020/01/gin-tonic.png",
            "strImageAttribution": null,
            "strCreativeCommonsConfirmed": "No",
            "dateModified": null
        },
        {
            "idDrink": "178364",
            "strDrink": "Vodka Tonic",
            "strDrinkAlternate": null,
            "strTags": null,
            "strVideo": null,
            "strCategory": "Cocktail",
            "strIBA": null,
            "strAlcoholic": "Alcoholic",
            "strGlass": "Highball glass",
            "strInstructions": "Wash and cut 1 wedge and 1 slice of lime or lemon.\r\nFill a tumbler with fresh ice.\r\nPour the desired dose of vodka and top up with the tonic.\r\nSqueeze the lime wedge into the glass and decorate with the slice.\r\nThat's all, very simple: it's just the recipe for happiness!",
            "strInstructionsES": null,
            "strInstructionsDE": "1 Keil und 1 Limetten- oder Zitronenscheibe waschen und schneiden.\r\nFüllen Sie einen Tumbler mit frischem Eis.\r\nGießen Sie die gewünschte Dosis Wodka ein und füllen Sie das Tonic auf.\r\nLimettenschnitz ins Glas drücken und mit der Scheibe dekorieren.\r\nDas ist alles, ganz einfach: Es ist einfach das Rezept für Glück!",
            "strInstructionsFR": null,
            "strInstructionsIT": "Lavate e tagliate 1 spicchio e 1 fetta di lime o limone.\r\nColmate un tumbler con ghiaccio fresco.\r\nVersate la dose di vodka desiderata e colmate con la tonica.\r\nStrizzate lo spicchio di lime dentro il bicchiere e decorate con la fetta.\r\nTutto qui, molto semplice: è solo la ricetta della felicità!",
            "strInstructionsZH-HANS": null,
            "strInstructionsZH-HANT": null,
            "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/9koz3f1643821062.jpg",
            "strIngredient1": "Vodka",
            "strIngredient2": "Tonic Water",
            "strIngredient3": "Lemon Peel",
            "strIngredient4": null,
            "strIngredient5": null,
            "strIngredient6": null,
            "strIngredient7": null,
            "strIngredient8": null,
            "strIngredient9": null,
            "strIngredient10": null,
            "strIngredient11": null,
            "strIngredient12": null,
            "strIngredient13": null,
            "strIngredient14": null,
            "strIngredient15": null,
            "strMeasure1": "4 cl",
            "strMeasure2": "10 cl",
            "strMeasure3": "1 Slice",
            "strMeasure4": "",
            "strMeasure5": "",
            "strMeasure6": "",
            "strMeasure7": "",
            "strMeasure8": null,
            "strMeasure9": null,
            "strMeasure10": null,
            "strMeasure11": null,
            "strMeasure12": null,
            "strMeasure13": null,
            "strMeasure14": null,
            "strMeasure15": null,
            "strImageSource": "https://www.bernabei.it/media/mixology/vodka%20tonic.jpg",
            "strImageAttribution": null,
            "strCreativeCommonsConfirmed": "No",
            "dateModified": null
        },
        {
            "idDrink": "178363",
            "strDrink": "Vodka Lemon",
            "strDrinkAlternate": null,
            "strTags": null,
            "strVideo": null,
            "strCategory": "Cocktail",
            "strIBA": null,
            "strAlcoholic": "Alcoholic",
            "strGlass": "Highball glass",
            "strInstructions": "The vodka lemon is prepared directly in a highball glass or in a large tumbler: put 6-7 ice cubes in the glass, pour the vodka, lemonade and mix with a bar spoon. Finally decorate with a slice of lemon and, if you prefer, add a few mint leaves. Your vodka lemon is ready to be served.",
            "strInstructionsES": null,
            "strInstructionsDE": "Der Wodka Lemon wird direkt in einem Longdrinkglas oder in einem großen Tumbler zubereitet: 6-7 Eiswürfel in das Glas geben, Wodka, Limonade aufgießen und mit einem Barlöffel mixen. Zum Schluss mit einer Zitronenscheibe dekorieren und nach Belieben ein paar Minzeblätter hinzufügen. Ihr Wodka Lemon ist servierfertig.",
            "strInstructionsFR": null,
            "strInstructionsIT": "La vodka lemon si prepara direttamente in un bicchiere highball o in un tumbler grande: mettete nel bicchiere 6-7 cubetti di ghiaccio, versate la vodka, la limonata e mescolate con un bar spoon. Infine decorate con una fetta di limone e, se preferite, aggiungete qualche fogliolina di menta. Il vostro vodka lemon è pronto per essere servito.",
            "strInstructionsZH-HANS": null,
            "strInstructionsZH-HANT": null,
            "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/mql55h1643820632.jpg",
            "strIngredient1": "Vodka",
            "strIngredient2": "Lemon Juice",
            "strIngredient3": "Lemon Peel",
            "strIngredient4": "Ice",
            "strIngredient5": null,
            "strIngredient6": null,
            "strIngredient7": null,
            "strIngredient8": null,
            "strIngredient9": null,
            "strIngredient10": null,
            "strIngredient11": null,
            "strIngredient12": null,
            "strIngredient13": null,
            "strIngredient14": null,
            "strIngredient15": null,
            "strMeasure1": "5 cl",
            "strMeasure2": "7 cl",
            "strMeasure3": "1 Slice",
            "strMeasure4": "cubes",
            "strMeasure5": "",
            "strMeasure6": "",
            "strMeasure7": "",
            "strMeasure8": null,
            "strMeasure9": null,
            "strMeasure10": null,
            "strMeasure11": null,
            "strMeasure12": null,
            "strMeasure13": null,
            "strMeasure14": null,
            "strMeasure15": null,
            "strImageSource": "https://blog.giallozafferano.it/lacucinadiliberte/wp-content/uploads/2019/09/Vodka-lemon-d.jpg",
            "strImageAttribution": null,
            "strCreativeCommonsConfirmed": "No",
            "dateModified": null
        },
        {
            "idDrink": "178362",
            "strDrink": "Vodka Slime",
            "strDrinkAlternate": null,
            "strTags": null,
            "strVideo": null,
            "strCategory": "Cocktail",
            "strIBA": null,
            "strAlcoholic": "Alcoholic",
            "strGlass": "Highball glass",
            "strInstructions": "Fill glass with ice. Add vodka, 7-up then finish with the lime juice.",
            "strInstructionsES": null,
            "strInstructionsDE": null,
            "strInstructionsFR": null,
            "strInstructionsIT": null,
            "strInstructionsZH-HANS": null,
            "strInstructionsZH-HANT": null,
            "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/apex461643588115.jpg",
            "strIngredient1": "Sprite",
            "strIngredient2": "Lime Juice",
            "strIngredient3": "Vodka",
            "strIngredient4": null,
            "strIngredient5": null,
            "strIngredient6": null,
            "strIngredient7": null,
            "strIngredient8": null,
            "strIngredient9": null,
            "strIngredient10": null,
            "strIngredient11": null,
            "strIngredient12": null,
            "strIngredient13": null,
            "strIngredient14": null,
            "strIngredient15": null,
            "strMeasure1": "1 cup",
            "strMeasure2": "1/2 shot",
            "strMeasure3": "1 1/2 shot",
            "strMeasure4": "",
            "strMeasure5": "",
            "strMeasure6": "",
            "strMeasure7": "",
            "strMeasure8": null,
            "strMeasure9": null,
            "strMeasure10": null,
            "strMeasure11": null,
            "strMeasure12": null,
            "strMeasure13": null,
            "strMeasure14": null,
            "strMeasure15": null,
            "strImageSource": "https://giggledam.com/wp-content/uploads/2020/07/4909D8D9-F78E-4391-B7A2-B383CA57D69F.jpeg",
            "strImageAttribution": null,
            "strCreativeCommonsConfirmed": "No",
            "dateModified": null
        },
        {
            "idDrink": "178360",
            "strDrink": "Lemon Elderflower Spritzer",
            "strDrinkAlternate": null,
            "strTags": "Summer, Fresh, Refreshing",
            "strVideo": null,
            "strCategory": "Cocktail",
            "strIBA": null,
            "strAlcoholic": "Alcoholic",
            "strGlass": "Highball glass",
            "strInstructions": "Pour all ingredients over ice, stir and enjoy!\r\n",
            "strInstructionsES": null,
            "strInstructionsDE": null,
            "strInstructionsFR": null,
            "strInstructionsIT": null,
            "strInstructionsZH-HANS": null,
            "strInstructionsZH-HANT": null,
            "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/125w0o1630407389.jpg",
            "strIngredient1": "Elderflower cordial",
            "strIngredient2": "Vodka",
            "strIngredient3": "Soda Water",
            "strIngredient4": "Fresh Lemon Juice",
            "strIngredient5": null,
            "strIngredient6": null,
            "strIngredient7": null,
            "strIngredient8": null,
            "strIngredient9": null,
            "strIngredient10": null,
            "strIngredient11": null,
            "strIngredient12": null,
            "strIngredient13": null,
            "strIngredient14": null,
            "strIngredient15": null,
            "strMeasure1": "2 tsp",
            "strMeasure2": "1 shot",
            "strMeasure3": "1/3 cup",
            "strMeasure4": "Top",
            "strMeasure5": "",
            "strMeasure6": "",
            "strMeasure7": "",
            "strMeasure8": null,
            "strMeasure9": null,
            "strMeasure10": null,
            "strMeasure11": null,
            "strMeasure12": null,
            "strMeasure13": null,
            "strMeasure14": null,
            "strMeasure15": null,
            "strImageSource": "https://www.instagram.com/p/CNLYC2_sdlk",
            "strImageAttribution": null,
            "strCreativeCommonsConfirmed": "No",
            "dateModified": null
        }
    ]
}